sequenceDiagram
    participant U as Клиент
    participant D as Гейтвей D
    participant A as Сервис A<br/>(авторизации)
    participant B as Сервис B<br/>(профилей)
    participant C as Сервис C<br/>(заказов)
    U->>+D: GET /v1/state<br/>Authorization: Bearer #60;token#62;
    D->>+A: GET /v1/auth<br/><token>
    A-->>-D: { status, user_id }
    par
        alt Профиль не найден в кэше
            D->>+B: GET /v1/profiles/{user_id}
            B-->>-D: 200 OK<br/>Cache-Control: #60;параметры#62;<br/>{ profile }
        end
    and 
        D->>+C: GET /v1/orders?user_id=#60;user_id#62;<br/>If-None-Match: #60;ревизия#62;
        alt Неверная ревизия
            C-->>D: 200 OK<br/>ETag: #60;ревизия#62;<br/>{ orders }
        else Ревизия актуальна
            C-->>D: 304 Not Modified
        end
        deactivate C
    end
    D-->>-U: { profile, orders }
