sequenceDiagram
    participant M as Model
    participant V as View
    participant U as User
    participant C as Controller
    M ->> V: Определяет
    V ->> U: Представляет
    U ->> C: Взаимодействует
    C ->> M: Обновляет
    