sequenceDiagram
    participant U as Client
    participant D as Gateway D
    participant A as Authorization<br/>Service A
    participant B as User Profiles<br/>Service B
    participant C as Orders<br/>Service C
    U->>+D: POST /v1/orders HTTP/1.1<br/>If-Match: #60;revision#62;<br/>Authorization: Bearer #60;token#62;
    D->>+A: GET /v1/auth<br/><token>
    A-->>-D: { status, user_id }
    D->>+C: POST /v1/orders?user_id=#60;user_id#62;<br/>If-Match: #60;revision#62;
    alt Actual revision
        C-->>D: 201 Created<br/>Content-Location: /v1/orders?user_id=<user_id><br/>ETag: #60;New revision#62;<br/>{ orders }
    else Wrong Revision
        C-->>D: 409 Conflict
    end
    deactivate C
    D-->>-U: 201 Created<br/>ETag: #60;New revision#62;<br/>{ orders }
