sequenceDiagram
    participant M as Model
    participant V as View
    participant U as User
    participant C as Controller
    M ->> V: Determines
    V ->> U: Presents
    U ->> C: Interacts
    C ->> M: Updates
    